workflowVersion: 1.0.0
sources:
    ppdb-openapi.yaml:
        inputs:
            - location: ../ppdb-openapi.yaml
targets:
    my-first-target:
        target: typescript
        source: ppdb-openapi.yaml
