/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type DeleteNotesNoteIDRequest = {
    noteID: number;
};

export type DeleteNotesNoteIDResponse = {
    httpMeta: components.HTTPMetadata;
};

/** @internal */
export namespace DeleteNotesNoteIDRequest$ {
    export const inboundSchema: z.ZodType<DeleteNotesNoteIDRequest, z.ZodTypeDef, unknown> = z
        .object({
            noteID: z.number().int(),
        })
        .transform((v) => {
            return {
                noteID: v.noteID,
            };
        });

    export type Outbound = {
        noteID: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteNotesNoteIDRequest> = z
        .object({
            noteID: z.number().int(),
        })
        .transform((v) => {
            return {
                noteID: v.noteID,
            };
        });
}

/** @internal */
export namespace DeleteNotesNoteIDResponse$ {
    export const inboundSchema: z.ZodType<DeleteNotesNoteIDResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteNotesNoteIDResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
            };
        });
}
