/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type DeleteBreedsBreedIDRequest = {
    breedID: number;
};

export type DeleteBreedsBreedIDResponse = {
    httpMeta: components.HTTPMetadata;
};

/** @internal */
export namespace DeleteBreedsBreedIDRequest$ {
    export const inboundSchema: z.ZodType<DeleteBreedsBreedIDRequest, z.ZodTypeDef, unknown> = z
        .object({
            breedID: z.number().int(),
        })
        .transform((v) => {
            return {
                breedID: v.breedID,
            };
        });

    export type Outbound = {
        breedID: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteBreedsBreedIDRequest> = z
        .object({
            breedID: z.number().int(),
        })
        .transform((v) => {
            return {
                breedID: v.breedID,
            };
        });
}

/** @internal */
export namespace DeleteBreedsBreedIDResponse$ {
    export const inboundSchema: z.ZodType<DeleteBreedsBreedIDResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteBreedsBreedIDResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
            };
        });
}
