/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetBreedsRequest = {
    page?: number | undefined;
    limit?: number | undefined;
    sort?: string | undefined;
};

export type GetBreedsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * A list of breeds
     */
    breeds?: Array<components.Breed> | undefined;
};

/** @internal */
export namespace GetBreedsRequest$ {
    export const inboundSchema: z.ZodType<GetBreedsRequest, z.ZodTypeDef, unknown> = z
        .object({
            page: z.number().int().default(1),
            limit: z.number().int().default(10),
            sort: z.string().optional(),
        })
        .transform((v) => {
            return {
                page: v.page,
                limit: v.limit,
                ...(v.sort === undefined ? null : { sort: v.sort }),
            };
        });

    export type Outbound = {
        page: number;
        limit: number;
        sort?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBreedsRequest> = z
        .object({
            page: z.number().int().default(1),
            limit: z.number().int().default(10),
            sort: z.string().optional(),
        })
        .transform((v) => {
            return {
                page: v.page,
                limit: v.limit,
                ...(v.sort === undefined ? null : { sort: v.sort }),
            };
        });
}

/** @internal */
export namespace GetBreedsResponse$ {
    export const inboundSchema: z.ZodType<GetBreedsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Breeds: z.array(components.Breed$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Breeds === undefined ? null : { breeds: v.Breeds }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Breeds?: Array<components.Breed$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetBreedsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            breeds: z.array(components.Breed$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.breeds === undefined ? null : { Breeds: v.breeds }),
            };
        });
}
