/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type PutAnimalsAnimalIDRequest = {
    animalID: number;
    animal: components.Animal;
};

export type PutAnimalsAnimalIDResponse = {
    httpMeta: components.HTTPMetadata;
};

/** @internal */
export namespace PutAnimalsAnimalIDRequest$ {
    export const inboundSchema: z.ZodType<PutAnimalsAnimalIDRequest, z.ZodTypeDef, unknown> = z
        .object({
            animalID: z.number().int(),
            Animal: components.Animal$.inboundSchema,
        })
        .transform((v) => {
            return {
                animalID: v.animalID,
                animal: v.Animal,
            };
        });

    export type Outbound = {
        animalID: number;
        Animal: components.Animal$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutAnimalsAnimalIDRequest> = z
        .object({
            animalID: z.number().int(),
            animal: components.Animal$.outboundSchema,
        })
        .transform((v) => {
            return {
                animalID: v.animalID,
                Animal: v.animal,
            };
        });
}

/** @internal */
export namespace PutAnimalsAnimalIDResponse$ {
    export const inboundSchema: z.ZodType<PutAnimalsAnimalIDResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PutAnimalsAnimalIDResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
            };
        });
}
