/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Not Found
 */
export type NotFoundErrorData = {
    message?: string | undefined;
};

/**
 * Not Found
 */
export class NotFoundError extends Error {
    /** The original data that was passed to this error instance. */
    data$: NotFoundErrorData;

    constructor(err: NotFoundErrorData) {
        super("");
        this.data$ = err;

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "NotFoundError";
    }
}

/** @internal */
export namespace NotFoundError$ {
    export const inboundSchema: z.ZodType<NotFoundError, z.ZodTypeDef, unknown> = z
        .object({
            message: z.string().optional(),
        })
        .transform((v) => {
            return new NotFoundError({
                ...(v.message === undefined ? null : { message: v.message }),
            });
        });

    export type Outbound = {
        message?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, NotFoundError> = z
        .instanceof(NotFoundError)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    message: z.string().optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.message === undefined ? null : { message: v.message }),
                    };
                })
        );
}
