/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Breed = {
    breedID?: number | undefined;
    breedname?: string | undefined;
    avgtime?: string | undefined;
    avgcost?: number | undefined;
};

/** @internal */
export namespace Breed$ {
    export const inboundSchema: z.ZodType<Breed, z.ZodTypeDef, unknown> = z
        .object({
            breedID: z.number().int().optional(),
            breedname: z.string().optional(),
            avgtime: z.string().optional(),
            avgcost: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.breedID === undefined ? null : { breedID: v.breedID }),
                ...(v.breedname === undefined ? null : { breedname: v.breedname }),
                ...(v.avgtime === undefined ? null : { avgtime: v.avgtime }),
                ...(v.avgcost === undefined ? null : { avgcost: v.avgcost }),
            };
        });

    export type Outbound = {
        breedID?: number | undefined;
        breedname?: string | undefined;
        avgtime?: string | undefined;
        avgcost?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Breed> = z
        .object({
            breedID: z.number().int().optional(),
            breedname: z.string().optional(),
            avgtime: z.string().optional(),
            avgcost: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.breedID === undefined ? null : { breedID: v.breedID }),
                ...(v.breedname === undefined ? null : { breedname: v.breedname }),
                ...(v.avgtime === undefined ? null : { avgtime: v.avgtime }),
                ...(v.avgcost === undefined ? null : { avgcost: v.avgcost }),
            };
        });
}
