/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
    apiKeyAuth?: string | undefined;
};

/** @internal */
export namespace Security$ {
    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
        .object({
            ApiKeyAuth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.ApiKeyAuth === undefined ? null : { apiKeyAuth: v.ApiKeyAuth }),
            };
        });

    export type Outbound = {
        ApiKeyAuth?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            apiKeyAuth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.apiKeyAuth === undefined ? null : { ApiKeyAuth: v.apiKeyAuth }),
            };
        });
}
